### ISSUE TITLE
Problem with running the first example of the course

### ISSUE THREAD

**Issue by ghost** [kamranayub/pluralsight-ravendb-4-getting-started#1]
Hi!
When I'm launching the application (03 - Document Store) with `dotnet run` , I'm getting an exception. 

`Unhandled Exception: CsvHelper.ReaderException: An unexpected error occurred. ---> System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at CsvHelper.TypeConversion.DateTimeConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData) in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\TypeConversion\DateTimeConverter.cs:line 33
   at lambda_method(Closure )   at CsvHelper.Expressions.RecordCreator.Create[T]() in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\Expressions\RecordCreator.cs:line 44
   at CsvHelper.CsvReader.<GetRecords>d__631.MoveNext() in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\CsvReader.cs:line 1055   --- End of inner exception stack trace ---
   at CsvHelper.Configuration.Configuration.<>c.<.ctor>b__148_4(CsvHelperException exception) in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\Configuration\Configuration.cs:line 106`

I'm using dotnet version 2.1.101

**Comment by kamranayub** [comment]
Hi, thanks for logging an issue. Just curious, what is your regions typical
date format? And is your PC set to a specific region in it's settings
(Languages and Time Zones)?

**Comment by kamranayub** [comment]
Hey @NPolikurov did you get this figured out?

**Comment by HailTheHughes** [comment]
Hi @kamranayub, I hit the same issue as @NPolikurov. 

I've had to change the dates from 05/21/2015 to 2015-05-21 as the format used is for US dates I think.  If you use the ISO date format it should hopefully work everywhere :-).

I've also had an issue with .net core 2.1.  I've had to remove Microsoft.DotNet.Watcher.Tools from the csproj file.

**Comment by kamranayub** [comment]
Ah good to know!

**Comment by kamranayub** [comment]
Fixed in #2
